dist: xenial
sudo: false
language: python
cache: pip
python:
- 3.7
matrix:
  fast_finish: true
  include:
    - python: 3.7
      env: REQ="https://github.com/django/django/archive/master.zip#egg=Django"
    - python: 3.7
      env: REQ="Django>=2.2,<3.0"
    - python: 3.6
      env: REQ="Django>=2.2,<3.0"
    - python: 3.7
      env: REQ="Django>=1.11,<2.0"
    - python: 3.6
      env: REQ="Django>=1.11,<2.0"
    - python: 3.5
      env: REQ="Django>=1.11,<2.0"
    - python: 2.7
      env: REQ="Django>=1.11,<2.0"
    - python: 3.7
      env: REQ="black flake8"
      install:
        - pip install black flake8
      script:
        - flake8 .
        - black --check specifications tests
  allow_failures:
    - env: REQ="https://github.com/django/django/archive/master.zip#egg=Django"
install:
- pip install -U pip setuptools wheel
- pip install $REQ
- python setup.py install
script: cd tests && ./manage.py test -v 2 testapp && cd ..
